MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.01

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,37 +4,60 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
+    - CONFIG=osx_python2.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "FUHqHlE+7vTB5y1esm96DGCL/s+g2fnpVvFxJ6aTKDGj6OoYYBkMwUbKm1I47Yo3IZHNmrDv0pbYNLBIsBTBS2e3lZDCUuSOYGFFoFBD1ZAbCtixl4pAmUyz1Bfl1Y6LCcQWZqcv3fCKzErp+NXBD/4GsyP85mbTVlmMIaNknSsiG1meXWMBeeuy7/qwVBBHWelV5GmIvRaJK4WeD7LLUg0jPcWnomyrJzrpaor515L1I/lt+YRpj/Sw6hsgPJJMIH9LK8ltEWhllcYZTsE0/vu1oPjS7+sdxkfRJYaXt938Ch+APyNzaOtHDOtypOs/OAmxhTLSt6lOyma9XVsfdXSAmqBo0BfzFdFj4nNsuZi3q+CZM6pyiT07Vxxv4MN0nQZy/796LqVjeC6q2o8dVmCgTHFvZaS/PVJC3NMTL6h+Q3OpWJDYypks4MWJmzt/FBFBnnSTNEdZQRAQRQmv9h78BfYZpfsTKK8Lci98FoRiFrEfVA9D8wdfjoTPBXcmPvM36P+ITcACsrmAUvsKQe055wlc4M8Qr4k5W3pEXzjVq+bU+YTM/exYFA8TLbxEqSaOECLOWBI+Rev86tH5VCkb5eJMZGEg1oDt6Tng7XUHQAY/niLqVmInB3hElugNzn+z7TvqnlB+1rRPTgKH9f168C7+LbhEskGSGWyYpyc="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
